### PR TITLE
Correct module name from `imap.imap` to `imap`

### PR DESCRIPTION
**Pull request by nordlow**
FYI, @kinke.

### CODE REVIEW

**Comment by kinke** [comment]
I think that'd be the nice variant. Another, non-breaking option would be to rename the file to `imap/imap.d`.

**Comment by kinke** [comment]
Or maybe combine the two variants - fixing up the module ID *and* adding a deprecated `imap/imap.d` module publicly importing the imap package.

**Comment by Geod24** [comment]
I quite dislike top level modules because they tend to conflict easily with symbol. Why don't we have those in a namespace, e.g. `symmetry.imap` ?

**Comment by adamdruppe** [comment]
Yeah, single-name modules should be outright banned from the package repo since they're so prone to trouble.

symmetry.imap is a fine name.

and then the other subpackages should really be under it too.

**Comment by kinke** [comment]
Okay that makes totally sense to me. So to me it's a question whether to just rename the file to `imap/imap.d` for backwards compatibility, or going directly with the breaking `symmetry` prefix. - For context, this invalid module ID came up for a private Symmetry project, where `import imap;` (wrongly) worked, but later caused a codegen error with LDC wrt. the `imap.imap` ModuleInfo.

**Comment by Geod24** [comment]
Use the symmetry prefix and provide a deprecated module that publicly import it. It will work for everyone and there is no downside to it. We don't even have to make a new major.

**Comment by nordlow** [comment]
Thanks for all the feedback. 

In what file shall I use 

`module symmetry.imap;`

and in what file shall I use the existing

`module imap;`

? On of them should be package.d, right. Should the other file be named imap.d and lie besides package.d?

**Comment by Geod24** [comment]
```
git mv source/imap/ source/symmetry/
git mv source/symmetry/package.d source/symmetry/imap.d
sed -i -e 's/module imap/module symmetry.imap/g' source/symmetry/imap.d
echo >source/imap.d <<EOF
deprecated("Use module `symmetry.imap` instead")
module imap;
public import symmetry.imap;
EOF
```

Something along those lines.

**Comment by nordlow** [comment]
The changes I've made now gives

```
source/symmetry/imap.d(2,1): Error: module `symmetry.imap` from file source/symmetry/imap.d conflicts with package name imap
```

and I have no clue how to resolve this. Need help. 

Am I missing a `package.d` file somewhere?

**Comment by kinke** [comment]
> Use the symmetry prefix and provide a deprecated module that publicly import it. It will work for everyone and there is no downside to it. We don't even have to make a new major.

That's assuming everyone just imported the `imap.imap` package, not individual modules.

**Comment by nordlow** [comment]
> > Use the symmetry prefix and provide a deprecated module that publicly import it. It will work for everyone and there is no downside to it. We don't even have to make a new major.
> 
> That's assuming everyone just imported the `imap.imap` package, not individual modules.

Exactly. If not, we have to create a copies of those modules aswell. Shall we bother with that, @Geod24?

**Comment by Geod24** [comment]
@kinke : Right, I was looking solely at the diff, not the other modules.
Then yeah, we would need to create wrapper for all the other modules, which is a bit of noise, but a one-time cost.
That is, of course, if everyone agrees having a top level `symmetry` package is a good idea (and it would keep in line with the previous `kaleidic` approach we used).

**Comment by adamdruppe** [comment]
> and I have no clue how to resolve this. Need help.

this is a design flaw in the language. if you compile individually, it will allow imap.d to be `module symmetry.imap` but if you compile it together with the submodules, then the compiler arbitrarily and capriciously *requires* the file to be called `package.d` (unlike filenames in any other situation)

so this file:

[source/symmetry/imap.d](https://github.com/symmetryinvestments/imap-d/pull/120/files#diff-83fcb3f26da9f303bfbe81cef3fbd8db864560559ee26331ab83bf8564f01532)

must be renamed to package.d to silence this error.

I can't find the bug for this specifically but this random thing has caused a few bugs to be opened but this is by design so they won't fix it...

**Comment by nordlow** [comment]
> this is a design flaw in the language. if you compile individually, it will allow imap.d to be `module symmetry.imap` but if you compile it together with the submodules, then the compiler arbitrarily and capriciously _requires_ the file to be called `package.d` (unlike filenames in any other situation)

Thank you.

Have adjusted and `dub tests` pass locally now.

I'll create the remainder of the wrapper modules next.

Update. Ehh, CI fails at

https://github.com/symmetryinvestments/imap-d/actions/runs/3265512913/jobs/5367843519#step:6:119

as

```
source/imap.d(3,15): Error: unable to read module `imap`
source/imap.d(3,15):        Expected 'symmetry/imap.d' or 'symmetry/imap/package.d' in one of the following import paths:
```

. Update: Ahh, I see now. Going green now.

**Comment by nordlow** [comment]
Should be ready now. Unfortunately git doesn't figure out a smart final diff for this one. But I believe this is ok if the review is split up into

f262ac9 and https://github.com/symmetryinvestments/imap-d/compare/f262ac91d0501fb5cf73fc948db7be5183b1d851..a7958eece6c2745e03bf7167f84bb3e5c547446d

**Comment by nordlow** [comment]
Ping.
